version: "0.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: howto_frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app

